const { EMPLOYMENT_TYPES } = require("../../../constants/employmentTypes");

/**
 * Loan product registry — the single place where a product's behaviour is defined.
 *
 * Every product shares the same three sections:
 *   Income Details · Existing Loan Exposure · Personal Details
 * Only "Loan Requirements" differ per product (`loanRequirements` below),
 * so adding a new product means adding one block here + its requirement files
 * inside the product folder (modules/loans/<product>/<name>.requirements.*.js).
 *
 * income:
 *   "salaried"     — only salaried income fields apply        (Personal Loan)
 *   "selfEmployed" — business + professional income fields    (Business Loan)
 *   "employment"   — salaried + business + professional       (Home Loan, LAP, FDI Loan)
 *
 * loanAmountRequired / loanTenureRequired default to true; the Credit Card
 * product sets both to false because it has no amount or tenure.
 *
 * multiValueFields lists the repeatable fields of a product's "Loan
 * Requirements" section (checkbox lists / "Add" rows). A client may send them
 * as a real array or as a CSV string — the service normalises both to an array.
 */
const LOAN_PRODUCTS = {
  personal: {
    product: "personal",
    loanType: "Personal Loan",
    loanTypeEnum: ["Personal Loan", "Business Loan", "Home Loan", "Vehicle Loan", "Education Loan", "Other"],
    route: "/api/personal-loan",
    employmentTypes: EMPLOYMENT_TYPES.personal,
    employmentTypeRequired: false,
    employmentTypeDefault: "Salaried",
    employmentTypeMessage: "Employment type must be Salaried",
    income: "salaried",
    personalDetailsRequired: false,
    exposureRequired: false,
    loanRequirements: null,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary must be a non-negative number" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  business: {
    product: "business",
    loanType: "Business Loan",
    loanTypeEnum: ["Business Loan"],
    route: "/api/business-loan",
    employmentTypes: EMPLOYMENT_TYPES.business,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "selfEmployed",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: null,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary must be a non-negative number" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: true,
  },

  home: {
    product: "home",
    loanType: "Home Loan",
    loanTypeEnum: ["Home Loan"],
    route: "/api/home-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "buyingProperty",
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be positive",
    loanTenureMin: 3,
    loanTenureMessage: "Loan tenure (in months) must be at least 3",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  commercialPurchase: {
    product: "commercialPurchase",
    loanType: "Commercial Purchase",
    loanTypeEnum: ["Commercial Purchase"],
    route: "/api/commercial-purchase",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "commercialPurchase",
    loanAmountMin: 1,
    loanAmountMessage: "Required loan amount is required and must be positive",
    loanTenureMin: 3,
    loanTenureMessage: "Loan tenure (in months) must be at least 3",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  lap: {
    product: "lap",
    loanType: "Loan Against Property",
    loanTypeEnum: ["Loan Against Property"],
    route: "/api/loan-against-property",
    employmentTypes: EMPLOYMENT_TYPES.lap,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "collateralProperty",
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required loan amount is ₹1,00,000",
    loanTenureMin: 3,
    loanTenureMessage: "Select loan tenure (minimum 3 months)",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  workingCapital: {
    product: "workingCapital",
    loanType: "Working Capital",
    loanTypeEnum: ["Working Capital"],
    route: "/api/working-capital",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    // Same "collateral property" section as LAP — shared, not duplicated.
    loanRequirements: "collateralProperty",
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required loan amount is ₹1,00,000",
    loanTenureMin: 3,
    loanTenureMessage: "Select loan tenure (minimum 3 months)",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  odCcLimit: {
    product: "odCcLimit",
    loanType: "OD / CC Limit",
    loanTypeEnum: ["OD / CC Limit"],
    route: "/api/od-cc-limit",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    // Same "collateral property" section as LAP / Working Capital — shared, not duplicated.
    loanRequirements: "collateralProperty",
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required OD / CC limit is ₹1,00,000",
    // The dashboard asks for a renewal tenure "between 3-40 years" (= 36-480 months).
    loanTenureMin: 36,
    loanTenureMax: 480,
    loanTenureMessage: "Renewal tenure must be between 3 and 40 years",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  loanAgainstShare: {
    product: "loanAgainstShare",
    loanType: "Loan Against Share",
    loanTypeEnum: ["Loan Against Share"],
    route: "/api/loan-against-share",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "loanAgainstShare",
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required loan amount is ₹1,00,000",
    // The dashboard offers 1-7 years (+ "More than 7 years").
    loanTenureMin: 3,
    loanTenureMessage: "Loan tenure (in months) must be at least 3",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  filmFunding: {
    product: "filmFunding",
    loanType: "Film Funding",
    loanTypeEnum: ["Film Funding"],
    route: "/api/film-funding",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "filmFunding",
    // Repeatable requirement fields — the service turns a CSV string into an array.
    multiValueFields: ["filmLanguages", "starCastNames"],
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required funds amount is ₹1,00,000",
    // The dashboard offers 1-10 years (+ "More than 10 years").
    loanTenureMin: 3,
    loanTenureMessage: "Select the required tenure (minimum 3 months)",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  fdiLoan: {
    product: "fdiLoan",
    loanType: "FDI Loan",
    loanTypeEnum: ["FDI Loan"],
    route: "/api/fdi-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "fdiLoan",
    loanAmountMin: 1000000000,
    loanAmountMessage: "Required fund amount must be at least ₹100 crore",
    loanTenureMin: 12,
    loanTenureMax: 132,
    loanTenureMessage: "Required fund tenure must be between 1 and 11 years",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  leaseRentalDiscounting: {
    product: "leaseRentalDiscounting",
    loanType: "Lease Rental Discounting",
    loanTypeEnum: ["Lease Rental Discounting"],
    route: "/api/lease-rental-discounting",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "leaseRentalDiscounting",
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required loan amount is ₹1,00,000",
    loanTenureMin: 3,
    loanTenureMessage: "Select loan tenure (minimum 3 months)",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  balanceTransfer: {
    product: "balanceTransfer",
    loanType: "Balance Transfer",
    loanTypeEnum: ["Balance Transfer"],
    route: "/api/balance-transfer",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "balanceTransfer",
    loanAmountMin: 1,
    loanAmountMessage: "Balance transfer amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Balance transfer tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  projectLoan: {
    product: "projectLoan",
    loanType: "Project Loan",
    loanTypeEnum: ["Project Loan"],
    route: "/api/project-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "projectLoan",
    loanAmountMin: 1,
    loanAmountMessage: "Project loan amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Project loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  vehicleLoan: {
    product: "vehicleLoan",
    loanType: "Vehicle Loan",
    loanTypeEnum: ["Vehicle Loan"],
    route: "/api/vehicle-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "vehicleLoan",
    loanAmountMin: 1,
    loanAmountMessage: "Vehicle loan amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Vehicle loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  educationLoan: {
    product: "educationLoan",
    loanType: "Education Loan",
    loanTypeEnum: ["Education Loan"],
    route: "/api/education-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "educationLoan",
    loanAmountMin: 1,
    loanAmountMessage: "Education loan amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Education loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  goldLoan: {
    product: "goldLoan",
    loanType: "Gold Loan",
    loanTypeEnum: ["Gold Loan"],
    route: "/api/gold-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "goldLoan",
    // The pledged gold IS the collateral, so a market value is mandatory —
    // it reuses the LAP-family field name (only one section is active per
    // product, so there is no conflict with the LAP section).
    loanAmountMin: 1,
    loanAmountMessage: "Required loan amount is required and must be positive",
    // The dashboard offers 1-10 years (+ "More than 10 years").
    loanTenureMin: 3,
    loanTenureMessage: "Select loan tenure (minimum 3 months)",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  npaLoan: {
    product: "npaLoan",
    loanType: "NPA Loan",
    loanTypeEnum: ["NPA Loan"],
    route: "/api/npa-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "npaLoan",
    // An NPA application describes an EXISTING stressed account — no fresh
    // amount or tenure is asked on the dashboard, so both are optional here
    // (same pattern as Credit Card).
    loanAmountRequired: false,
    loanTenureRequired: false,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure must be a positive number of months",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  creditCard: {
    product: "creditCard",
    loanType: "Credit Card",
    loanTypeEnum: ["Credit Card"],
    route: "/api/credit-card",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "creditCard",
    loanAmountRequired: false,
    loanTenureRequired: false,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },
};

module.exports = { LOAN_PRODUCTS };
