const { EMPLOYMENT_TYPES } = require("../../shared/constants/employmentTypes");

/**
 * Loan product registry — the single place where a product's behaviour is defined.
 *
 * Every product shares the same three sections:
 *   Income Details · Existing Loan Exposure · Personal Details
 * Only "Loan Requirements" differ per product (`loanRequirements` below),
 * so adding a new product means adding one block here + its requirement files
 * under schema/requirements<ProductName>.js and validators/requirements<ProductName>.js.
 *
 * income:
 *   "salaried"     — only salaried income fields apply        (Personal Loan)
 *   "selfEmployed" — business + professional income fields    (Business Loan)
 *   "employment"   — salaried + business + professional       (Home Loan, LAP)
 *
 * loanAmountRequired / loanTenureRequired default to true; the Credit Card
 * product sets both to false because it has no amount or tenure.
 */
const LOAN_PRODUCTS = {
  personal: {
    product: "personal",
    loanType: "Personal Loan",
    loanTypeEnum: ["Personal Loan", "Business Loan", "Home Loan", "Car Loan", "Education Loan", "Other"],
    route: "/api/personal-loan",
    employmentTypes: EMPLOYMENT_TYPES.personal,
    employmentTypeRequired: false,
    employmentTypeDefault: "Salaried",
    employmentTypeMessage: "Employment type must be Salaried",
    income: "salaried",
    personalDetailsRequired: false,
    exposureRequired: false,
    loanRequirements: null,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary must be a non-negative number" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  business: {
    product: "business",
    loanType: "Business Loan",
    loanTypeEnum: ["Business Loan"],
    route: "/api/business-loan",
    employmentTypes: EMPLOYMENT_TYPES.business,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "selfEmployed",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: null,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary must be a non-negative number" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: true,
  },

  home: {
    product: "home",
    loanType: "Home Loan",
    loanTypeEnum: ["Home Loan"],
    route: "/api/home-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "buyingProperty",
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be positive",
    loanTenureMin: 3,
    loanTenureMessage: "Loan tenure (in months) must be at least 3",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  lap: {
    product: "lap",
    loanType: "Loan Against Property",
    loanTypeEnum: ["Loan Against Property"],
    route: "/api/loan-against-property",
    employmentTypes: EMPLOYMENT_TYPES.lap,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: true,
    loanRequirements: "collateralProperty",
    loanAmountMin: 100000,
    loanAmountMessage: "Minimum required loan amount is ₹1,00,000",
    loanTenureMin: 3,
    loanTenureMessage: "Select loan tenure (minimum 3 months)",
    salary: { min: 12001, message: "Monthly net salary must be greater than 12,000" },
    gstFormat: true,
    adultApplicant: true,
    normalizeBankOnResponse: false,
  },

  balanceTransfer: {
    product: "balanceTransfer",
    loanType: "Balance Transfer",
    loanTypeEnum: ["Balance Transfer"],
    route: "/api/balance-transfer",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "balanceTransfer",
    loanAmountMin: 1,
    loanAmountMessage: "Balance transfer amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Balance transfer tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  projectLoan: {
    product: "projectLoan",
    loanType: "Project Loan",
    loanTypeEnum: ["Project Loan"],
    route: "/api/project-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "projectLoan",
    loanAmountMin: 1,
    loanAmountMessage: "Project loan amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Project loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  carLoan: {
    product: "carLoan",
    loanType: "Car Loan",
    loanTypeEnum: ["Car Loan"],
    route: "/api/car-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "carLoan",
    loanAmountMin: 1,
    loanAmountMessage: "Car loan amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Car loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  educationLoan: {
    product: "educationLoan",
    loanType: "Education Loan",
    loanTypeEnum: ["Education Loan"],
    route: "/api/education-loan",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "educationLoan",
    loanAmountMin: 1,
    loanAmountMessage: "Education loan amount is required and must be positive",
    loanTenureMin: 1,
    loanTenureMessage: "Education loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },

  creditCard: {
    product: "creditCard",
    loanType: "Credit Card",
    loanTypeEnum: ["Credit Card"],
    route: "/api/credit-card",
    employmentTypes: EMPLOYMENT_TYPES.home,
    employmentTypeRequired: true,
    employmentTypeMessage: "Employment type is invalid",
    income: "employment",
    personalDetailsRequired: true,
    exposureRequired: false,
    loanRequirements: "creditCard",
    loanAmountRequired: false,
    loanTenureRequired: false,
    loanAmountMin: 1,
    loanAmountMessage: "Loan amount is required and must be a positive number",
    loanTenureMin: 1,
    loanTenureMessage: "Loan tenure is required and must be a positive number of months",
    salary: { min: 0, message: "Monthly salary is required" },
    gstFormat: false,
    adultApplicant: false,
    normalizeBankOnResponse: false,
  },
};

module.exports = { LOAN_PRODUCTS };
